### ISSUE TITLE
Our Staff page

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#10]
**User Story**
As a physically-impaired skier with specific needs related to the instruction, I want to see a list of the staff and their qualifications to determine whether the school can cater to my needs. 

**Acceptance Criteria**
- [ ] Site has a dedicated “Our Staff” section or page which clearly displays the details of individual staff members and their training level.
- [ ] Staff information is laid out in an easily readable format which is responsive on all devices.

**Tasks**
- [ ] Create separate “Our Staff” page 
- [ ] Create responsive list of staff members with name and brief description about qualifications using Bootstrap cards and grid.
