### ISSUE TITLE
Social Events section on homepage

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#11]
**User Story**
As a solo holidaymaker, I want to see a list of social events or group lessons open to singles so that I can have a good social experience. 

**Acceptance Criteria**
- [ ] The homepage has a dedicated section for social events with relevant details

**Tasks**
- [ ] Create static section for a list of upcoming events/socials on the homepage
- [ ] Develop list with Bootstrap (more cards?)
- [ ] Make list responsive
