### ISSUE TITLE
High quality images and descriptions

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#12]
**User Story**
As a potential booker, I want to see good quality images and descriptions about what is on offer so I can determine whether this is the school I want to commit to.

**Acceptance Criteria** 
- [x] Homepage features a hero image relevant to ski holidays/instructio
- [x] Engaging descriptions of all lessons and clinics are displayed clearly and concisely 
- [x] The pages are uncluttered and attractive

**Tasks:**
- [x] Add high-quality hero image, and images for lesson/clinic cards
- [x] Embed descriptions about the school and the lessons/clinics on offer within the site content
- [x] Design and implement homepage layout with prominently featured images and descriptions
