### ISSUE TITLE
User friendly navigation and responsive design

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#2]
**User Story**
As a holidaymaker, I want to be able to navigate through the site easily on all types of devices so I can make bookings quickly.

**Acceptance Criteria**
- [x] Create navigation section within the header for each site page which allows users to click to navigate to various pages/sections, including “Home”, “Hiring”, “Lessons”
- [x] “Book Now” call to action button
- [x] When in a particular page, the name of the page stands out compared to other navigation links. Navigation is intuitive. 

**Tasks**
- [x] Develop a Bootstrap navbar which is responsive on various screen sizes.
- [x] Ensure all pages and key sections are easily accessible from anywhere on the site.
