### ISSUE TITLE
Lesson options displayed in responsive section of homepage

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#3]
**User Story**
As a holidaymaker on a budget, I want to see a list of the types of lessons available and their prices so that I can determine the best lesson option for my child. 

**Acceptance Criteria** 
- [x] The home page displays a list of the different types of lessons and instruction available, sorted by level.
- [x] Each item in the list includes the name, price, and a brief description.
- [x] The list is responsive and looks good on all devices

**Tasks**
- [x] Add an HTML section on the homepage dedicated to lesson types available.
- [x] Display pricing for different options
- [x] Style the events using Bootstrap (cards, grid)
- [x] Populate lessons section with sample information on cards
