### ISSUE TITLE
Lesson options displayed in dedicated section on homepage

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#4]
**User Story**
As a holidaymaker on a budget, I want to see a list of the types of lessons available and their prices so that I can determine the best lesson option for my child. 

**Acceptance Criteria**
- [ ] The home page displays a list of the different types of lessons and instruction available, sorted by level.
- [ ] Each item in the list includes the name, price, and a brief description. (duration?)
- [ ] The list is responsive and looks good on all devices

**Tasks**
- [ ] Add an HTML section on the homepage dedicated to lesson types available.
- [ ] Display pricing for different options (and any discounts available), name and brief description
- [ ] Style the events using Bootstrap (cards, grid)
