### ISSUE TITLE
Clinic options displayed in responsive section of homepage

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#5]
**User Story**
As an experienced skier looking to develop my skills in a high-performance clinic, I want to see a list of the types of clinics available and their prices so that I can determine the one best suited to me.

**Acceptance Criteria**
- [x] The home page displays a list of the different types of clinics available, sorted by level.
- [x] Each item in the list includes the name, price, and a brief description. 
- [x] The list is responsive and looks good on all devices

**Tasks**
- [x] Add an HTML section on the homepage dedicated to clinic types available.
- [x] Display pricing for different options (and any discounts available), name and brief description
- [x] Style the events using Bootstrap (cards, grid)
