### ISSUE TITLE
Contact details, location and opening hours

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#6]
**User Story**
As a local business owner, I would like to be able to quickly identify the contact details and information about the ski school so I can include this in recommendations to my own customers.

**Acceptance Criteria**
- [x] The site has a dedicated section for contact details, address and opening hours.
- [x] This section is visible and accessible from anywhere on the website.

**Tasks**
- [x] Develop a footer section for contact details, address and opening hours.
- [x] Ensure this section is visible on all pages, adhering to common design standards.
