### ISSUE TITLE
Responsive booking form for lessons & clinics

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#7]
**User Story**
As a holidaymaker, I need a clear and easy-to-use form to book lessons for multiple people so that I can book lessons for our family.

**Acceptance Criteria**
- [ ] Develop separate booking form page with fields for name, email, date and preferred type of instruction. (Accessed via button on main page - Call to Action)
- [ ] Link the form to a success page to let customers know they have filled it out successfully. 
- [ ] The booking form and success page must be responsive and look good on all devices.

**Tasks**
- [ ] Create booking.html form section OR page with relevant input fields for name, email, date and a select drop-down list for instruction type.
- [ ] Link output from form to a simple success page confirming form submission. 
- [ ] Utilise Bootstrap grid and classes to make the form responsive on all screen sizes.
