### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#8]
**User Story**
As a holidaymaker looking to book lessons, I want to read testimonials from others who have used the ski school so that I can feel confident when booking.

**Acceptance Criteria**
- [x] Website includes a separate testimonials page dedicated to past customer reviews.
- [x] The testimonials are clearly visible and are presented in a format that is easy to read, with key info (e.g. name, quote)

**Tasks**
- [x] Create separate page for customer testimonials
- [x] Style the testimonials using Bootstrap (cards, grid) to ensure responsiveness 
- [x] Add sample testimonials
