### ISSUE TITLE
Hiring Page

### ISSUE THREAD

**Issue by DTT2411** [DTT2411/CI-Portfolio-Project-1#9]
**User Story**
As a qualified ski instructor, I want to know how to apply so that I can secure work with the ski school.

**Acceptance Criteria**
- [x] Site has a separate “Hiring” page which provides information on current hiring opportunities
- [x] Instructors interested in applying can submit their details via form to initiate a job application process

**Tasks**
- [x] Develop separate html page for Hiring
- [x] Create short form for submitting personal details to apply
- [x] Make form responsive
